# Generated by Django 3.2.9 on 2021-11-18 04:17

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('EGB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='dateTimeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now),
        ),
    ]
