# Generated by Django 3.2.9 on 2021-11-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EGB', '0002_match_datetimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='site',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
