EGB = 'EGB'
BET_WINNER = 'BETWINNER'
BET_WINNER_URL = 'https://betwinner1.com/LineFeed/Get1x2_VZip?sports=40&count=100&lng=us&tf=2200000&mode=4&country=43&partner=152&getEmpty=true'
TELE_BOT_TOKEN = '2116690014:AAESHuHCYk8N4rX-zcKM5O9eDmqmSg6nHO0'
TELE_CHAT_ID = '-644075779'

BW_CSGO = 'CS:GO'
BW_LOL = 'LOL'
BW_STAR_CRAFT = 'StarCraft II'
BW_DOTA2 = 'Dota 2'
BW_KOG = 'King of Glory'
BW_VAL = 'Valorant'
BW_PUBG = 'PUBG'
BW_AOR = 'Arena of Valor'

EGB_CSGO = 'CS:GO'
EGB_LOL = 'LOL'
EGB_STAR_CRAFT = 'StarCraft2'
EGB_DOTA2 = 'Dota 2'
EGB_KOG = 'KingOfGlory'
EGB_VAL = 'Valorant'
EGB_PUBG = 'PUBG'
EGB_AOR = 'Arena of Valor'

BET_CSGO = 'CS:GO'
BET_LOL = 'LOL'
BET_STAR_CRAFT = 'StarCraft'
BET_DOTA2 = 'DOTA2'
BET_KOG = 'KingOfGlory'
BET_VAL = 'Valorant'
BET_PUBG = 'PUBG'
BET_AOR = 'ArenaOfValor'